"""initial schema

Revision ID: 4ad282c52705
Revises: 
Create Date: 2026-06-11 13:01:06.370137

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '4ad282c52705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Control-plane schemas (FDD data designs: auth / tenancy / iam / audit;
    # platform holds cross-cutting tables like idempotency keys).
    for schema_name in ("auth", "tenancy", "iam", "audit", "platform"):
        op.execute(f"CREATE SCHEMA IF NOT EXISTS {schema_name}")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('event_id', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'service', name='actor_type', native_enum=False, length=16), nullable=False),
    sa.Column('actor_id', sa.Text(), nullable=False),
    sa.Column('subject_type', sa.Text(), nullable=False),
    sa.Column('subject_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Text(), nullable=True),
    sa.Column('decision', sa.Enum('allow', 'deny', 'n/a', name='audit_decision', native_enum=False, length=8), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_module', sa.Text(), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.Column('chain_hash', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('event_id', 'occurred_at', name=op.f('pk_events')),
    schema='audit',
    postgresql_partition_by='RANGE (occurred_at)'
    )
    # Monthly range partitioning (FDD §2.3.4): the DEFAULT partition absorbs
    # all rows until the audit-archiver introduces month partitions.
    op.execute("CREATE TABLE audit.events_default PARTITION OF audit.events DEFAULT")
    op.create_index('ix_audit_events_action', 'events', ['action'], unique=False, schema='audit')
    op.create_index('ix_audit_events_actor', 'events', ['actor_id'], unique=False, schema='audit')
    op.create_index('ix_audit_events_subject', 'events', ['subject_type', 'subject_id'], unique=False, schema='audit')
    op.create_index('ix_audit_events_tenant_time', 'events', ['tenant_id', 'occurred_at', 'event_id'], unique=False, schema='audit')
    op.create_table('login_throttle',
    sa.Column('email_hash', sa.LargeBinary(), nullable=False),
    sa.Column('consecutive_failures', sa.SmallInteger(), nullable=False),
    sa.Column('backoff_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('email_hash', name=op.f('pk_login_throttle')),
    schema='auth'
    )
    op.create_table('permissions',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('domain', sa.Text(), nullable=False),
    sa.Column('resource', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('owning_module', sa.Text(), nullable=False),
    sa.Column('scope_levels', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('service_only', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_permissions')),
    schema='iam'
    )
    op.create_index('ix_permissions_domain', 'permissions', ['domain', 'resource', 'action'], unique=False, schema='iam')
    op.create_table('users',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'deactivated', name='user_status', native_enum=False, length=16), nullable=False),
    sa.Column('deactivate_reason', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_tenant_id', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    schema='iam'
    )
    op.create_index('ix_users_status_created', 'users', ['status', 'created_at'], unique=False, schema='iam')
    op.create_table('idempotency_keys',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('payload_hash', sa.LargeBinary(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', 'endpoint', name=op.f('pk_idempotency_keys')),
    schema='platform'
    )
    op.create_index('ix_idempotency_created', 'idempotency_keys', ['created_at'], unique=False, schema='platform')
    op.create_table('resources',
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('resource_class', sa.Enum('compute', 'storage', name='resource_class', native_enum=False, length=16), nullable=False),
    sa.Column('form', sa.Enum('physical', 'logical', name='resource_form', native_enum=False, length=16), nullable=False),
    sa.Column('descriptor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_ref', sa.Text(), nullable=True),
    sa.Column('health', sa.Enum('unprobed', 'reachable', 'unreachable', name='resource_health', native_enum=False, length=16), nullable=True),
    sa.Column('last_probe_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('active', 'decommissioned', name='resource_status', native_enum=False, length=20), nullable=False),
    sa.Column('labels', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('decommissioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_resources')),
    sa.UniqueConstraint('name', name=op.f('uq_resources_name')),
    schema='tenancy'
    )
    op.create_index('ix_resources_kind_status', 'resources', ['resource_class', 'form', 'status', 'created_at'], unique=False, schema='tenancy')
    op.create_table('tenants',
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'suspended', 'archived', name='tenant_status', native_enum=False, length=16), nullable=False),
    sa.Column('suspend_reason', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('namespace_ref', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('name', name=op.f('uq_tenants_name')),
    schema='tenancy'
    )
    op.create_index('ix_tenants_status_created', 'tenants', ['status', 'created_at'], unique=False, schema='tenancy')
    op.create_table('login_codes',
    sa.Column('code_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('code_hash', sa.LargeBinary(), nullable=False),
    sa.Column('salt', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('issued', 'consumed', 'expired', name='login_code_status', native_enum=False, length=16), nullable=False),
    sa.Column('expire_reason', sa.Enum('ttl', 'superseded', 'attempts_exhausted', 'user_deactivated', name='login_code_expire_reason', native_enum=False, length=24), nullable=True),
    sa.Column('attempt_count', sa.SmallInteger(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_ip_hash', sa.LargeBinary(), nullable=True),
    sa.CheckConstraint('attempt_count <= 5', name=op.f('ck_login_codes_attempt_count_max')),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.user_id'], name=op.f('fk_login_codes_user_id_users')),
    sa.PrimaryKeyConstraint('code_id', name=op.f('pk_login_codes')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_login_codes_user_id'), 'login_codes', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_login_codes_status_expires', 'login_codes', ['status', 'expires_at'], unique=False, schema='auth')
    op.create_index('uq_login_codes_one_issued_per_user', 'login_codes', ['user_id'], unique=True, schema='auth', postgresql_where=sa.text("status = 'issued'"))
    op.create_table('sessions',
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('status', sa.Enum('active', 'expired', 'revoked', name='session_status', native_enum=False, length=16), nullable=False),
    sa.Column('revoked_reason', sa.Enum('logout', 'admin_revoke', 'user_deactivated', name='session_revoked_reason', native_enum=False, length=24), nullable=True),
    sa.Column('active_tenant_id', sa.Text(), nullable=True),
    sa.Column('client_user_agent', sa.Text(), nullable=True),
    sa.Column('client_device_label', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_tenant_id'], ['tenancy.tenants.tenant_id'], name=op.f('fk_sessions_active_tenant_id_tenants')),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.user_id'], name=op.f('fk_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_sessions_token_hash')),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_sessions_user_id'), 'sessions', ['user_id'], unique=False, schema='auth')
    op.create_index('ix_sessions_active_expiry', 'sessions', ['idle_expires_at'], unique=False, schema='auth', postgresql_where=sa.text("status = 'active'"))
    op.create_index('ix_sessions_user_status', 'sessions', ['user_id', 'status'], unique=False, schema='auth')
    op.create_table('access_reviews',
    sa.Column('review_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('review_type', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'failed', name='review_status', native_enum=False, length=16), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('requested_by', sa.Text(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenancy.tenants.tenant_id'], name=op.f('fk_access_reviews_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('review_id', name=op.f('pk_access_reviews')),
    schema='iam'
    )
    op.create_index('ix_access_reviews_tenant', 'access_reviews', ['tenant_id', 'created_at'], unique=False, schema='iam')
    op.create_table('roles',
    sa.Column('role_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role_type', sa.Enum('builtin', 'custom', name='role_type', native_enum=False, length=16), nullable=False),
    sa.Column('scope_type', sa.Enum('platform', 'tenant', name='role_scope_type', native_enum=False, length=16), nullable=False),
    sa.Column('scope_tenant_id', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scope_tenant_id'], ['tenancy.tenants.tenant_id'], name=op.f('fk_roles_scope_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_roles')),
    schema='iam'
    )
    op.create_index('uq_roles_name_per_scope', 'roles', ['scope_type', 'scope_tenant_id', 'name'], unique=True, schema='iam', postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_table('resource_bindings',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('binding_mode', sa.Enum('exclusive', 'shared', name='binding_mode', native_enum=False, length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'released', name='binding_status', native_enum=False, length=16), nullable=False),
    sa.Column('bound_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bound_by', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('released_by', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['tenancy.resources.resource_id'], name=op.f('fk_resource_bindings_resource_id_resources')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenancy.tenants.tenant_id'], name=op.f('fk_resource_bindings_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('binding_id', name=op.f('pk_resource_bindings')),
    schema='tenancy'
    )
    op.create_index('ix_bindings_tenant_status', 'resource_bindings', ['tenant_id', 'status', 'bound_at'], unique=False, schema='tenancy')
    op.create_index('uq_bindings_exclusive_resource', 'resource_bindings', ['resource_id'], unique=True, schema='tenancy', postgresql_where=sa.text("binding_mode = 'exclusive' AND status = 'active'"))
    op.create_index('uq_bindings_tenant_resource_active', 'resource_bindings', ['tenant_id', 'resource_id'], unique=True, schema='tenancy', postgresql_where=sa.text("status = 'active'"))
    op.create_table('resource_credentials',
    sa.Column('resource_id', sa.Text(), nullable=False),
    sa.Column('secret_encrypted', sa.LargeBinary(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['tenancy.resources.resource_id'], name=op.f('fk_resource_credentials_resource_id_resources')),
    sa.PrimaryKeyConstraint('resource_id', name=op.f('pk_resource_credentials')),
    schema='tenancy'
    )
    op.create_table('access_review_entries',
    sa.Column('review_id', sa.Text(), nullable=False),
    sa.Column('entry_no', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('grant', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('asset_class', sa.Text(), nullable=False),
    sa.Column('last_access_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anomalies', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['iam.access_reviews.review_id'], name=op.f('fk_access_review_entries_review_id_access_reviews')),
    sa.PrimaryKeyConstraint('review_id', 'entry_no', name=op.f('pk_access_review_entries')),
    schema='iam'
    )
    op.create_index('ix_access_review_entries_review', 'access_review_entries', ['review_id', 'entry_no'], unique=False, schema='iam')
    op.create_table('persona_templates',
    sa.Column('template_key', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_builtin_role', sa.Text(), nullable=False),
    sa.Column('permission_keys', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('platform_scoped', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['default_builtin_role'], ['iam.roles.role_id'], name=op.f('fk_persona_templates_default_builtin_role_roles')),
    sa.PrimaryKeyConstraint('template_key', name=op.f('pk_persona_templates')),
    schema='iam'
    )
    op.create_table('role_bindings',
    sa.Column('binding_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('role_id', sa.Text(), nullable=False),
    sa.Column('scope_type', sa.Enum('platform', 'tenant', 'project', name='binding_scope_type', native_enum=False, length=16), nullable=False),
    sa.Column('scope_id', sa.Text(), nullable=True),
    sa.Column('origin', sa.Enum('direct', 'project_membership', name='binding_origin', native_enum=False, length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['iam.roles.role_id'], name=op.f('fk_role_bindings_role_id_roles')),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.user_id'], name=op.f('fk_role_bindings_user_id_users')),
    sa.PrimaryKeyConstraint('binding_id', name=op.f('pk_role_bindings')),
    schema='iam'
    )
    op.create_index('ix_role_bindings_role', 'role_bindings', ['role_id'], unique=False, schema='iam')
    op.create_index('ix_role_bindings_scope', 'role_bindings', ['scope_type', 'scope_id'], unique=False, schema='iam')
    op.create_index('ix_role_bindings_user_live', 'role_bindings', ['user_id'], unique=False, schema='iam', postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index('uq_role_bindings_unique_live', 'role_bindings', ['user_id', 'role_id', 'scope_type', 'scope_id'], unique=True, schema='iam', postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Text(), nullable=False),
    sa.Column('permission_key', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['permission_key'], ['iam.permissions.key'], name=op.f('fk_role_permissions_permission_key_permissions')),
    sa.ForeignKeyConstraint(['role_id'], ['iam.roles.role_id'], name=op.f('fk_role_permissions_role_id_roles')),
    sa.PrimaryKeyConstraint('role_id', 'permission_key', name=op.f('pk_role_permissions')),
    schema='iam'
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.Text(), nullable=False),
    sa.Column('default_storage_binding_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='project_status', native_enum=False, length=16), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_by', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['default_storage_binding_id'], ['tenancy.resource_bindings.binding_id'], name=op.f('fk_projects_default_storage_binding_id_resource_bindings')),
    sa.ForeignKeyConstraint(['owner_user_id'], ['iam.users.user_id'], name=op.f('fk_projects_owner_user_id_users')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenancy.tenants.tenant_id'], name=op.f('fk_projects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_projects_tenant_id_name')),
    schema='tenancy'
    )
    op.create_index('ix_projects_owner', 'projects', ['owner_user_id'], unique=False, schema='tenancy')
    op.create_index('ix_projects_tenant_status', 'projects', ['tenant_id', 'status', 'created_at'], unique=False, schema='tenancy')
    op.create_table('project_members',
    sa.Column('project_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('persona_templates', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('added_by', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.Text(), nullable=True),
    sa.CheckConstraint('array_length(persona_templates, 1) >= 1', name=op.f('ck_project_members_persona_templates_nonempty')),
    sa.ForeignKeyConstraint(['project_id'], ['tenancy.projects.project_id'], name=op.f('fk_project_members_project_id_projects')),
    sa.ForeignKeyConstraint(['user_id'], ['iam.users.user_id'], name=op.f('fk_project_members_user_id_users')),
    sa.PrimaryKeyConstraint('project_id', 'user_id', name=op.f('pk_project_members')),
    schema='tenancy'
    )
    op.create_index('ix_project_members_user', 'project_members', ['user_id'], unique=False, schema='tenancy')
    # ### end Alembic commands ###
    _seed()


def _seed() -> None:
    """Seed the permission catalog, built-in roles, and the ten persona
    templates (FDD §2.3: code-defined via migration at deploy). Sourced from
    app.services.catalog — the same structures the authz service evaluates,
    so catalog and code cannot drift."""
    from datetime import datetime, timezone

    from app.services.catalog import BUILTIN_ROLES, CATALOG, PERSONA_TEMPLATES

    now = datetime.now(timezone.utc)
    permissions_table = sa.table(
        "permissions",
        sa.column("key", sa.Text),
        sa.column("domain", sa.Text),
        sa.column("resource", sa.Text),
        sa.column("action", sa.Text),
        sa.column("description", sa.Text),
        sa.column("owning_module", sa.Text),
        sa.column("scope_levels", postgresql.ARRAY(sa.Text)),
        sa.column("service_only", sa.Boolean),
        schema="iam",
    )
    op.bulk_insert(
        permissions_table,
        [
            {
                "key": e.key,
                "domain": e.domain,
                "resource": e.resource,
                "action": e.action,
                "description": e.description,
                "owning_module": e.owning_module,
                "scope_levels": e.scope_levels,
                "service_only": e.service_only,
            }
            for e in CATALOG
        ],
    )

    roles_table = sa.table(
        "roles",
        sa.column("role_id", sa.Text),
        sa.column("name", sa.Text),
        sa.column("role_type", sa.Text),
        sa.column("scope_type", sa.Text),
        sa.column("scope_tenant_id", sa.Text),
        sa.column("description", sa.Text),
        sa.column("version", sa.Integer),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("created_by", sa.Text),
        schema="iam",
    )
    op.bulk_insert(
        roles_table,
        [
            {
                "role_id": role_id,
                "name": meta["name"],
                "role_type": "builtin",
                "scope_type": "platform",
                "scope_tenant_id": None,
                "description": meta["description"],
                "version": 1,
                "created_at": now,
                "created_by": "system:migration",
            }
            for role_id, meta in BUILTIN_ROLES.items()
        ],
    )

    templates_table = sa.table(
        "persona_templates",
        sa.column("template_key", sa.Text),
        sa.column("display_name", sa.Text),
        sa.column("description", sa.Text),
        sa.column("default_builtin_role", sa.Text),
        sa.column("permission_keys", postgresql.ARRAY(sa.Text)),
        sa.column("platform_scoped", sa.Boolean),
        sa.column("version", sa.Integer),
        schema="iam",
    )
    op.bulk_insert(
        templates_table,
        [
            {
                "template_key": t["template_key"],
                "display_name": t["display_name"],
                "description": t["description"],
                "default_builtin_role": t["default_builtin_role"],
                "permission_keys": t["permission_keys"],
                "platform_scoped": t["platform_scoped"],
                "version": 1,
            }
            for t in PERSONA_TEMPLATES
        ],
    )

    # Built-in roles are immutable at the database level too (FDD §2.3.4).
    op.execute(
        """
        CREATE OR REPLACE FUNCTION iam.forbid_builtin_role_mutation() RETURNS trigger AS $$
        BEGIN
            IF (TG_OP = 'DELETE' AND OLD.role_type = 'builtin')
               OR (TG_OP = 'UPDATE' AND OLD.role_type = 'builtin') THEN
                RAISE EXCEPTION 'builtin roles are immutable';
            END IF;
            IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_roles_builtin_immutable
            BEFORE UPDATE OR DELETE ON iam.roles
            FOR EACH ROW EXECUTE FUNCTION iam.forbid_builtin_role_mutation()
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_roles_builtin_immutable ON iam.roles")
    op.execute("DROP FUNCTION IF EXISTS iam.forbid_builtin_role_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_members_user', table_name='project_members', schema='tenancy')
    op.drop_table('project_members', schema='tenancy')
    op.drop_index('ix_projects_tenant_status', table_name='projects', schema='tenancy')
    op.drop_index('ix_projects_owner', table_name='projects', schema='tenancy')
    op.drop_table('projects', schema='tenancy')
    op.drop_table('role_permissions', schema='iam')
    op.drop_index('uq_role_bindings_unique_live', table_name='role_bindings', schema='iam', postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index('ix_role_bindings_user_live', table_name='role_bindings', schema='iam', postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_index('ix_role_bindings_scope', table_name='role_bindings', schema='iam')
    op.drop_index('ix_role_bindings_role', table_name='role_bindings', schema='iam')
    op.drop_table('role_bindings', schema='iam')
    op.drop_table('persona_templates', schema='iam')
    op.drop_index('ix_access_review_entries_review', table_name='access_review_entries', schema='iam')
    op.drop_table('access_review_entries', schema='iam')
    op.drop_table('resource_credentials', schema='tenancy')
    op.drop_index('uq_bindings_tenant_resource_active', table_name='resource_bindings', schema='tenancy', postgresql_where=sa.text("status = 'active'"))
    op.drop_index('uq_bindings_exclusive_resource', table_name='resource_bindings', schema='tenancy', postgresql_where=sa.text("binding_mode = 'exclusive' AND status = 'active'"))
    op.drop_index('ix_bindings_tenant_status', table_name='resource_bindings', schema='tenancy')
    op.drop_table('resource_bindings', schema='tenancy')
    op.drop_index('uq_roles_name_per_scope', table_name='roles', schema='iam', postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table('roles', schema='iam')
    op.drop_index('ix_access_reviews_tenant', table_name='access_reviews', schema='iam')
    op.drop_table('access_reviews', schema='iam')
    op.drop_index('ix_sessions_user_status', table_name='sessions', schema='auth')
    op.drop_index('ix_sessions_active_expiry', table_name='sessions', schema='auth', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='sessions', schema='auth')
    op.drop_table('sessions', schema='auth')
    op.drop_index('uq_login_codes_one_issued_per_user', table_name='login_codes', schema='auth', postgresql_where=sa.text("status = 'issued'"))
    op.drop_index('ix_login_codes_status_expires', table_name='login_codes', schema='auth')
    op.drop_index(op.f('ix_auth_login_codes_user_id'), table_name='login_codes', schema='auth')
    op.drop_table('login_codes', schema='auth')
    op.drop_index('ix_tenants_status_created', table_name='tenants', schema='tenancy')
    op.drop_table('tenants', schema='tenancy')
    op.drop_index('ix_resources_kind_status', table_name='resources', schema='tenancy')
    op.drop_table('resources', schema='tenancy')
    op.drop_index('ix_idempotency_created', table_name='idempotency_keys', schema='platform')
    op.drop_table('idempotency_keys', schema='platform')
    op.drop_index('ix_users_status_created', table_name='users', schema='iam')
    op.drop_table('users', schema='iam')
    op.drop_index('ix_permissions_domain', table_name='permissions', schema='iam')
    op.drop_table('permissions', schema='iam')
    op.drop_table('login_throttle', schema='auth')
    op.drop_index('ix_audit_events_tenant_time', table_name='events', schema='audit')
    op.drop_index('ix_audit_events_subject', table_name='events', schema='audit')
    op.drop_index('ix_audit_events_actor', table_name='events', schema='audit')
    op.drop_index('ix_audit_events_action', table_name='events', schema='audit')
    op.drop_table('events', schema='audit')
    # ### end Alembic commands ###
